### ISSUE TITLE
Metraixbeat on ELK 7.16.1

### ISSUE THREAD

**Issue by Hussain-ibm** [bhm-ibm/Metraixbeat#10]
Will this metraixbeat support on ELK 7.16.1?

**Comment by bhm-kyndryl** [comment]
Hi !

I dont know, but I assume that Yes, if metricbeat JSONs has not changed too much.

we are updating in few weeks in 7.16
If any issue, I will publish some updates ;-)

Bye

**Comment by bhm-kyndryl** [comment]
Hi !
We have updated in 7.17 without any issue.
We jumped quickly on 7.16 and it was also good ;-)
